// <auto-generated />
namespace Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_019));
        
        string IMigrationMetadata.Id
        {
            get { return "201311262159303_019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
