// <auto-generated />
namespace Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _008 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_008));
        
        string IMigrationMetadata.Id
        {
            get { return "201404061954329_008"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
